### ISSUE TITLE
Changes required to get diffusion model to run with current mesa

### ISSUE THREAD

**Issue by complexitysoftware** [mgoadric/diffusion-mesa#1]
I found there are a couple of changes needed to get the mesa-diffusion example to work.  I made the following changes:
server.py 
change line 3 to:
from mesa.visualization.UserParam import Slider
change lines 50-52 to:
    "evaporate": Slider("Evaporation Rate", 0.07, 0.01, 0.30, 0.01),
    "diffusion": Slider("Diffusion Rate", 0.3, 0.0, 1.0, 0.1),
    "initdrop": Slider("Initial Drop", 500, 100, 1000, 50),

model.py
change line 38 to:
        for contents, (x, y) in self.grid.coord_iter():

**Comment by mgoadric** [comment]
Thank you for this, I have not run mesa in many years. I will try these out and report back!
